# Session 1 : Pandas - manipulation et analyse de données

#### Master TIDE 2026-2027

1. Chargement des données
2. Exploration des données
3. Transformation des données
4. Filtrage des données
5. Recherche géographique

&copy; Francis Wolinski 2026

In [1]:
# imports
import numpy as np
import pandas as pd

## 1. Chargement des données

Dataset des communes françaises : `correspondance-code-insee-code-postal.csv`

Ecrire une fonction qui charge le fichier CSV en utilisant uniquement les 11 premières colonnes.

```python
def lecture_geo():
    pass
```

Utiliser la colonne "Code INSEE" comme index et trier selon l'index.

Vérifier le dataframe obtenu en exécutant les tests unitaires à la fin du notebook.

In [16]:
def lecture_geo():
    df = pd.read_csv("./data/correspondance-code-insee-code-postal.csv",
                     sep=";",
                     usecols=range(11),
                     index_col="Code INSEE")
    df = df.sort_index()
    return df

In [10]:
df = lecture_geo()
df

,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape
Code INSEE,,,,,,,,,,
01001,01400,L'ABERGEMENT-CLEMENCIAT,AIN,RHONE-ALPES,Commune simple,242.0,1565.0,0.8,"46.1534255214, 4.92611354223","{""type"": ""Polygon"", ""coordinates"": [[[4.926273..."
01002,01640,L'ABERGEMENT-DE-VAREY,AIN,RHONE-ALPES,Commune simple,483.0,912.0,0.2,"46.0091878776, 5.42801696363","{""type"": ""Polygon"", ""coordinates"": [[[5.430089..."
01004,01500,AMBERIEU-EN-BUGEY,AIN,RHONE-ALPES,Chef-lieu canton,379.0,2448.0,13.4,"45.9608475114, 5.3729257777","{""type"": ""Polygon"", ""coordinates"": [[[5.386190..."
01005,01330,AMBERIEUX-EN-DOMBES,AIN,RHONE-ALPES,Commune simple,290.0,1605.0,1.6,"45.9961799872, 4.91227250796","{""type"": ""Polygon"", ""coordinates"": [[[4.895580..."
01006,01300,AMBLEON,AIN,RHONE-ALPES,Commune simple,589.0,602.0,0.1,"45.7494989044, 5.59432017366","{""type"": ""Polygon"", ""coordinates"": [[[5.614854..."
...,...,...,...,...,...,...,...,...,...,...
97613,97650,M'TSANGAMOUJI,MAYOTTE,MAYOTTE,Chef-lieu canton,96.0,2155.0,5.0,"-12.7513099309, 45.0871696871","{""type"": ""Polygon"", ""coordinates"": [[[45.10168..."
97614,97670,OUANGANI,MAYOTTE,MAYOTTE,Chef-lieu canton,175.0,1828.0,6.6,"-12.8370955196, 45.1379095497","{""type"": ""Polygon"", ""coordinates"": [[[45.15401..."
97615,97610,PAMANDZI,MAYOTTE,MAYOTTE,Chef-lieu canton,52.0,426.0,9.1,"-12.7961353309, 45.2842063102","{""type"": ""Polygon"", ""coordinates"": [[[45.29645..."
97616,97640,SADA,MAYOTTE,MAYOTTE,Chef-lieu canton,130.0,1085.0,8.0,"-12.8611649609, 45.1185503145","{""type"": ""Polygon"", ""coordinates"": [[[45.13226..."
97617,97680,TSINGONI,MAYOTTE,MAYOTTE,Chef-lieu canton,147.0,3426.0,9.2,"-12.7821666736, 45.1344279083","{""type"": ""Polygon"", ""coordinates"": [[[45.15256..."

## 2. Exploration des données

Répondez à ces questions :

- Combien y a-t-il de départements ?
- Quelle est la commune la plus peuplée ? Quelle pourrait être l'explication ?
- Combien y a-t-il de statuts de communes et quels sont leur distribution ?
- Quelle commune possède le statut "Capitale d'état" ? Quel attribut partage-t-elle avec d'autres communes ? Que faudrait-il faire pour homogénéiser le dataset ?
- Quelle est la commune la plus haute ?
- Quelle commune a le nom le plus court et le plus long ?
- Quel est le nom de commune le plus fréquent ?

In [18]:
type(df["Département"])

pandas.Series

In [19]:
df["Département"].nunique()

101

In [21]:
df.loc[df["Population"].idxmax(), "Commune"]

'TOULOUSE'

In [22]:
df["Statut"].nunique()

6

In [23]:
df["Statut"].unique()

<ArrowStringArray>
[      'Commune simple',     'Chef-lieu canton',      'Sous-préfecture',
           'Préfecture', 'Préfecture de région',      'Capitale d'état']
Length: 6, dtype: str

In [24]:
df["Statut"].value_counts()

Statut
Commune simple          33421
Chef-lieu canton         2980
Sous-préfecture           240
Préfecture                 74
Préfecture de région       26
Capitale d'état             1
Name: count, dtype: int64

In [27]:
df.loc[df["Statut"] == "Capitale d'état", "Commune"]

Code INSEE
75101    PARIS-1ER-ARRONDISSEMENT
Name: Commune, dtype: str

In [28]:
df.loc[df["Commune"].str.endswith("ARRONDISSEMENT")]

,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape
Code INSEE,,,,,,,,,,
13201,13001,MARSEILLE--1ER-ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Préfecture de région,29.0,178.0,40.9,"43.2999009436, 5.38227869795","{""type"": ""Polygon"", ""coordinates"": [[[5.372144..."
13202,13002,MARSEILLE--2E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,6.0,364.0,25.7,"43.3126964178, 5.36364983265","{""type"": ""Polygon"", ""coordinates"": [[[5.373616..."
13203,13003,MARSEILLE--3E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,25.0,254.0,45.4,"43.3121200046, 5.38010981423","{""type"": ""Polygon"", ""coordinates"": [[[5.375021..."
13204,13004,MARSEILLE--4E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,58.0,288.0,47.1,"43.306733355, 5.40087488752","{""type"": ""Polygon"", ""coordinates"": [[[5.408970..."
13205,13005,MARSEILLE--5E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,35.0,218.0,44.5,"43.2928061953, 5.3975770959","{""type"": ""Polygon"", ""coordinates"": [[[5.391944..."
13206,13006,MARSEILLE--6E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,41.0,206.0,43.3,"43.2870989546, 5.38104785394","{""type"": ""Polygon"", ""coordinates"": [[[5.373816..."
13207,13007,MARSEILLE--7E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,35.0,584.0,35.9,"43.28251778, 5.36323440435","{""type"": ""Polygon"", ""coordinates"": [[[5.367986..."
13208,13008,MARSEILLE--8E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,62.0,2077.0,78.8,"43.2417271832, 5.37464436293","{""type"": ""Polygon"", ""coordinates"": [[[5.381535..."
13209,13009,MARSEILLE--9E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,206.0,6358.0,76.8,"43.2340834927, 5.45249683067","{""type"": ""Polygon"", ""coordinates"": [[[5.510186..."
13210,13010,MARSEILLE-10E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,100.0,1074.0,51.2,"43.2755155435, 5.42681101081","{""type"": ""Polygon"", ""coordinates"": [[[5.452243..."
13211,13011,MARSEILLE-11E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,177.0,3351.0,56.7,"43.2884471881, 5.48381466229","{""type"": ""Polygon"", ""coordinates"": [[[5.484103..."
13212,13012,MARSEILLE-12E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,118.0,1407.0,58.7,"43.3077683678, 5.43991567678","{""type"": ""Polygon"", ""coordinates"": [[[5.425802..."
13213,13013,MARSEILLE-13E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,648.0,2800.0,89.3,"43.3492780005, 5.43372238738","{""type"": ""Polygon"", ""coordinates"": [[[5.410528..."
13214,13014,MARSEILLE-14E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,137.0,1637.0,61.9,"43.3455018067, 5.39408915769","{""type"": ""Polygon"", ""coordinates"": [[[5.393184..."
13215,13015,MARSEILLE-15E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,124.0,1663.0,77.7,"43.358794754, 5.363407897","{""type"": ""Polygon"", ""coordinates"": [[[5.369125..."
13216,13016,MARSEILLE-16E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,104.0,1420.0,17.6,"43.3649054121, 5.31337828595","{""type"": ""Polygon"", ""coordinates"": [[[5.337730..."
69381,69001,LYON--1ER-ARRONDISSEMENT,RHONE,RHONE-ALPES,Préfecture de région,197.0,153.0,28.1,"45.7699284397, 4.82922464978","{""type"": ""Polygon"", ""coordinates"": [[[4.830490..."
69382,69002,LYON--2E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,166.0,340.0,29.8,"45.7492560394, 4.82617032549","{""type"": ""Polygon"", ""coordinates"": [[[4.818954..."
69383,69003,LYON--3E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,174.0,632.0,90.4,"45.7533552486, 4.86918522013","{""type"": ""Polygon"", ""coordinates"": [[[4.892285..."
69384,69004,LYON--4E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,223.0,288.0,34.4,"45.7786867581, 4.82396112689","{""type"": ""Polygon"", ""coordinates"": [[[4.812869..."
69385,69005,LYON--5E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,255.0,622.0,47.0,"45.7558317849, 4.8022536949","{""type"": ""Polygon"", ""coordinates"": [[[4.813486..."
69386,69006,LYON--6E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,168.0,378.0,49.6,"45.7728507239, 4.85207911437","{""type"": ""Polygon"", ""coordinates"": [[[4.839949..."
69387,69007,LYON--7E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,166.0,946.0,69.2,"45.7334098415, 4.83758495703","{""type"": ""Polygon"", ""coordinates"": [[[4.840545..."
69388,69008,LYON--8E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,175.0,682.0,76.3,"45.7342034691, 4.86935722305","{""type"": ""Polygon"", ""coordinates"": [[[4.849179..."
69389,69009,LYON--9E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,202.0,749.0,47.1,"45.7817805887, 4.80818327822","{""type"": ""Polygon"", ""coordinates"": [[[4.819695..."
75101,75001,PARIS-1ER-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Capitale d'état,33.0,181.0,17.6,"48.8626304852, 2.33629344655","{""type"": ""Polygon"", ""coordinates"": [[[2.344559..."
75102,75002,PARIS-2E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,36.0,99.0,22.4,"48.8679033789, 2.34410716666","{""type"": ""Polygon"", ""coordinates"": [[[2.350834..."
75103,75003,PARIS-3E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,35.0,116.0,35.7,"48.8630541318, 2.35936105897","{""type"": ""Polygon"", ""coordinates"": [[[2.368401..."
75104,75004,PARIS-4E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,33.0,160.0,28.2,"48.854228282, 2.35736193814","{""type"": ""Polygon"", ""coordinates"": [[[2.364320..."
75105,75005,PARIS-5E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,42.0,252.0,61.5,"48.8445086596, 2.34985938556","{""type"": ""Polygon"", ""coordinates"": [[[2.365944..."
75106,75006,PARIS-6E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,40.0,215.0,43.1,"48.8489680919, 2.33267089859","{""type"": ""Polygon"", ""coordinates"": [[[2.336591..."
75107,75007,PARIS-7E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,34.0,411.0,57.4,"48.8560825982, 2.31243868773","{""type"": ""Polygon"", ""coordinates"": [[[2.316633..."
75108,75008,PARIS-8E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,39.0,385.0,40.3,"48.8725272666, 2.31258256042","{""type"": ""Polygon"", ""coordinates"": [[[2.320781..."
75109,75009,PARIS-9E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,44.0,218.0,60.3,"48.8768961624, 2.33746024139","{""type"": ""Polygon"", ""coordinates"": [[[2.325754..."
75110,75010,PARIS-10E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,45.0,288.0,95.9,"48.8760285569, 2.36111290456","{""type"": ""Polygon"", ""coordinates"": [[[2.363856..."
75111,75011,PARIS-11E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,43.0,366.0,152.7,"48.8594154976, 2.37874106024","{""type"": ""Polygon"", ""coordinates"": [[[2.399114..."
75112,75012,PARIS-12E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,49.0,1636.0,142.9,"48.8351562307, 2.41980703497","{""type"": ""Polygon"", ""coordinates"": [[[2.461247..."
75113,75013,PARIS-13E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,46.0,713.0,182.0,"48.8287176845, 2.36246822852","{""type"": ""Polygon"", ""coordinates"": [[[2.343909..."
75114,75014,PARIS-14E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,63.0,560.0,137.2,"48.8289932116, 2.32710088326","{""type"": ""Polygon"", ""coordinates"": [[[2.343909..."
75115,75015,PARIS-15E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,40.0,846.0,236.5,"48.8401554186, 2.29355937244","{""type"": ""Polygon"", ""coordinates"": [[[2.301320..."
75116,75016,PARIS-16E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,43.0,1641.0,169.4,"48.8603987604, 2.2620995594","{""type"": ""Polygon"", ""coordinates"": [[[2.262784..."
75117,75017,PARIS-17E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,40.0,563.0,168.5,"48.8873371665, 2.30748555949","{""type"": ""Polygon"", ""coordinates"": [[[2.295145..."
75118,75018,PARIS-18E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,57.0,604.0,200.6,"48.8927350746, 2.34871193387","{""type"": ""Polygon"", ""coordinates"": [[[2.327115..."
75119,75019,PARIS-19E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,63.0,674.0,184.8,"48.886868623, 2.38469432787","{""type"": ""Polygon"", ""coordinates"": [[[2.377012..."
75120,75020,PARIS-20E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,80.0,596.0,197.1,"48.8631867774, 2.40081982673","{""type"": ""Polygon"", ""coordinates"": [[[2.415973..."

In [29]:
df.loc[df["Commune"].str.contains("ARRONDISSEMENT", regex=False)]

,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape
Code INSEE,,,,,,,,,,
13201,13001,MARSEILLE--1ER-ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Préfecture de région,29.0,178.0,40.9,"43.2999009436, 5.38227869795","{""type"": ""Polygon"", ""coordinates"": [[[5.372144..."
13202,13002,MARSEILLE--2E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,6.0,364.0,25.7,"43.3126964178, 5.36364983265","{""type"": ""Polygon"", ""coordinates"": [[[5.373616..."
13203,13003,MARSEILLE--3E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,25.0,254.0,45.4,"43.3121200046, 5.38010981423","{""type"": ""Polygon"", ""coordinates"": [[[5.375021..."
13204,13004,MARSEILLE--4E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,58.0,288.0,47.1,"43.306733355, 5.40087488752","{""type"": ""Polygon"", ""coordinates"": [[[5.408970..."
13205,13005,MARSEILLE--5E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,35.0,218.0,44.5,"43.2928061953, 5.3975770959","{""type"": ""Polygon"", ""coordinates"": [[[5.391944..."
13206,13006,MARSEILLE--6E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,41.0,206.0,43.3,"43.2870989546, 5.38104785394","{""type"": ""Polygon"", ""coordinates"": [[[5.373816..."
13207,13007,MARSEILLE--7E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,35.0,584.0,35.9,"43.28251778, 5.36323440435","{""type"": ""Polygon"", ""coordinates"": [[[5.367986..."
13208,13008,MARSEILLE--8E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,62.0,2077.0,78.8,"43.2417271832, 5.37464436293","{""type"": ""Polygon"", ""coordinates"": [[[5.381535..."
13209,13009,MARSEILLE--9E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,206.0,6358.0,76.8,"43.2340834927, 5.45249683067","{""type"": ""Polygon"", ""coordinates"": [[[5.510186..."
13210,13010,MARSEILLE-10E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,100.0,1074.0,51.2,"43.2755155435, 5.42681101081","{""type"": ""Polygon"", ""coordinates"": [[[5.452243..."
13211,13011,MARSEILLE-11E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,177.0,3351.0,56.7,"43.2884471881, 5.48381466229","{""type"": ""Polygon"", ""coordinates"": [[[5.484103..."
13212,13012,MARSEILLE-12E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,118.0,1407.0,58.7,"43.3077683678, 5.43991567678","{""type"": ""Polygon"", ""coordinates"": [[[5.425802..."
13213,13013,MARSEILLE-13E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,648.0,2800.0,89.3,"43.3492780005, 5.43372238738","{""type"": ""Polygon"", ""coordinates"": [[[5.410528..."
13214,13014,MARSEILLE-14E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,137.0,1637.0,61.9,"43.3455018067, 5.39408915769","{""type"": ""Polygon"", ""coordinates"": [[[5.393184..."
13215,13015,MARSEILLE-15E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,124.0,1663.0,77.7,"43.358794754, 5.363407897","{""type"": ""Polygon"", ""coordinates"": [[[5.369125..."
13216,13016,MARSEILLE-16E--ARRONDISSEMENT,BOUCHES-DU-RHONE,PROVENCE-ALPES-COTE D'AZUR,Commune simple,104.0,1420.0,17.6,"43.3649054121, 5.31337828595","{""type"": ""Polygon"", ""coordinates"": [[[5.337730..."
69381,69001,LYON--1ER-ARRONDISSEMENT,RHONE,RHONE-ALPES,Préfecture de région,197.0,153.0,28.1,"45.7699284397, 4.82922464978","{""type"": ""Polygon"", ""coordinates"": [[[4.830490..."
69382,69002,LYON--2E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,166.0,340.0,29.8,"45.7492560394, 4.82617032549","{""type"": ""Polygon"", ""coordinates"": [[[4.818954..."
69383,69003,LYON--3E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,174.0,632.0,90.4,"45.7533552486, 4.86918522013","{""type"": ""Polygon"", ""coordinates"": [[[4.892285..."
69384,69004,LYON--4E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,223.0,288.0,34.4,"45.7786867581, 4.82396112689","{""type"": ""Polygon"", ""coordinates"": [[[4.812869..."
69385,69005,LYON--5E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,255.0,622.0,47.0,"45.7558317849, 4.8022536949","{""type"": ""Polygon"", ""coordinates"": [[[4.813486..."
69386,69006,LYON--6E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,168.0,378.0,49.6,"45.7728507239, 4.85207911437","{""type"": ""Polygon"", ""coordinates"": [[[4.839949..."
69387,69007,LYON--7E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,166.0,946.0,69.2,"45.7334098415, 4.83758495703","{""type"": ""Polygon"", ""coordinates"": [[[4.840545..."
69388,69008,LYON--8E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,175.0,682.0,76.3,"45.7342034691, 4.86935722305","{""type"": ""Polygon"", ""coordinates"": [[[4.849179..."
69389,69009,LYON--9E--ARRONDISSEMENT,RHONE,RHONE-ALPES,Commune simple,202.0,749.0,47.1,"45.7817805887, 4.80818327822","{""type"": ""Polygon"", ""coordinates"": [[[4.819695..."
75101,75001,PARIS-1ER-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Capitale d'état,33.0,181.0,17.6,"48.8626304852, 2.33629344655","{""type"": ""Polygon"", ""coordinates"": [[[2.344559..."
75102,75002,PARIS-2E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,36.0,99.0,22.4,"48.8679033789, 2.34410716666","{""type"": ""Polygon"", ""coordinates"": [[[2.350834..."
75103,75003,PARIS-3E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,35.0,116.0,35.7,"48.8630541318, 2.35936105897","{""type"": ""Polygon"", ""coordinates"": [[[2.368401..."
75104,75004,PARIS-4E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,33.0,160.0,28.2,"48.854228282, 2.35736193814","{""type"": ""Polygon"", ""coordinates"": [[[2.364320..."
75105,75005,PARIS-5E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,42.0,252.0,61.5,"48.8445086596, 2.34985938556","{""type"": ""Polygon"", ""coordinates"": [[[2.365944..."
75106,75006,PARIS-6E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,40.0,215.0,43.1,"48.8489680919, 2.33267089859","{""type"": ""Polygon"", ""coordinates"": [[[2.336591..."
75107,75007,PARIS-7E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,34.0,411.0,57.4,"48.8560825982, 2.31243868773","{""type"": ""Polygon"", ""coordinates"": [[[2.316633..."
75108,75008,PARIS-8E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,39.0,385.0,40.3,"48.8725272666, 2.31258256042","{""type"": ""Polygon"", ""coordinates"": [[[2.320781..."
75109,75009,PARIS-9E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,44.0,218.0,60.3,"48.8768961624, 2.33746024139","{""type"": ""Polygon"", ""coordinates"": [[[2.325754..."
75110,75010,PARIS-10E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,45.0,288.0,95.9,"48.8760285569, 2.36111290456","{""type"": ""Polygon"", ""coordinates"": [[[2.363856..."
75111,75011,PARIS-11E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,43.0,366.0,152.7,"48.8594154976, 2.37874106024","{""type"": ""Polygon"", ""coordinates"": [[[2.399114..."
75112,75012,PARIS-12E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,49.0,1636.0,142.9,"48.8351562307, 2.41980703497","{""type"": ""Polygon"", ""coordinates"": [[[2.461247..."
75113,75013,PARIS-13E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,46.0,713.0,182.0,"48.8287176845, 2.36246822852","{""type"": ""Polygon"", ""coordinates"": [[[2.343909..."
75114,75014,PARIS-14E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,63.0,560.0,137.2,"48.8289932116, 2.32710088326","{""type"": ""Polygon"", ""coordinates"": [[[2.343909..."
75115,75015,PARIS-15E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,40.0,846.0,236.5,"48.8401554186, 2.29355937244","{""type"": ""Polygon"", ""coordinates"": [[[2.301320..."
75116,75016,PARIS-16E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,43.0,1641.0,169.4,"48.8603987604, 2.2620995594","{""type"": ""Polygon"", ""coordinates"": [[[2.262784..."
75117,75017,PARIS-17E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,40.0,563.0,168.5,"48.8873371665, 2.30748555949","{""type"": ""Polygon"", ""coordinates"": [[[2.295145..."
75118,75018,PARIS-18E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,57.0,604.0,200.6,"48.8927350746, 2.34871193387","{""type"": ""Polygon"", ""coordinates"": [[[2.327115..."
75119,75019,PARIS-19E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,63.0,674.0,184.8,"48.886868623, 2.38469432787","{""type"": ""Polygon"", ""coordinates"": [[[2.377012..."
75120,75020,PARIS-20E-ARRONDISSEMENT,PARIS,ILE-DE-FRANCE,Chef-lieu canton,80.0,596.0,197.1,"48.8631867774, 2.40081982673","{""type"": ""Polygon"", ""coordinates"": [[[2.415973..."

In [30]:
df.loc[df["Commune"].str.len().idxmin(), "Commune"]

'Y'

In [31]:
df.loc[df["Commune"].str.len().idxmax(), "Commune"]

'SAINT-REMY-EN-BOUZEMONT-SAINT-GENEST-ET-ISSON'

In [36]:
df["Commune"].value_counts().index[0]

'SAINTE-COLOMBE'

## 3. Transformation des données

Effectuer les transformations suivantes :

- Convertir la colonne "Superficie" en km²
- Convertir la colonne "Altitude Moyenne" en entier
- Transformer la colonne "Statut" en catégorie ordonnée
- Créer la colonne "CP Ville" à partir du code postal et du nom de la commune
- Extraire la latitude et la longitude depuis la colonne "geo_point_2d"

In [38]:
df.info()

<class 'pandas.DataFrame'>
Index: 36742 entries, 01001 to 97617
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Code Postal       36742 non-null  str
 1   Commune           36742 non-null  str
 2   Département       36742 non-null  str
 3   Région            36742 non-null  str
 4   Statut            36742 non-null  str
 5   Altitude Moyenne  36742 non-null  float64
 6   Superficie        36742 non-null  float64
 7   Population        36742 non-null  float64
 8   geo_point_2d      36742 non-null  str
 9   geo_shape         36742 non-null  str
dtypes: float64(3), str(7)
memory usage: 28.4 MB

In [ ]:
pd.CategoricalDtype

In [41]:
df["Superficie"] /= 100
df["Altitude Moyenne"] = df["Altitude Moyenne"].astype(int)
cat_statut = pd.CategoricalDtype(categories=['Commune simple', 'Chef-lieu canton', 'Sous-préfecture', 'Préfecture', 'Préfecture de région', 'Capitale d\'état'],
                                 ordered=True)
df["Statut"] = df["Statut"].astype(cat_statut)
df["CP_Ville"] = df["Code Postal"] + " " + df["Commune"]
df

,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape,CP_Ville
Code INSEE,,,,,,,,,,,
01001,01400,L'ABERGEMENT-CLEMENCIAT,AIN,RHONE-ALPES,Commune simple,242,15.65,0.8,"46.1534255214, 4.92611354223","{""type"": ""Polygon"", ""coordinates"": [[[4.926273...",01400 L'ABERGEMENT-CLEMENCIAT
01002,01640,L'ABERGEMENT-DE-VAREY,AIN,RHONE-ALPES,Commune simple,483,9.12,0.2,"46.0091878776, 5.42801696363","{""type"": ""Polygon"", ""coordinates"": [[[5.430089...",01640 L'ABERGEMENT-DE-VAREY
01004,01500,AMBERIEU-EN-BUGEY,AIN,RHONE-ALPES,Chef-lieu canton,379,24.48,13.4,"45.9608475114, 5.3729257777","{""type"": ""Polygon"", ""coordinates"": [[[5.386190...",01500 AMBERIEU-EN-BUGEY
01005,01330,AMBERIEUX-EN-DOMBES,AIN,RHONE-ALPES,Commune simple,290,16.05,1.6,"45.9961799872, 4.91227250796","{""type"": ""Polygon"", ""coordinates"": [[[4.895580...",01330 AMBERIEUX-EN-DOMBES
01006,01300,AMBLEON,AIN,RHONE-ALPES,Commune simple,589,6.02,0.1,"45.7494989044, 5.59432017366","{""type"": ""Polygon"", ""coordinates"": [[[5.614854...",01300 AMBLEON
...,...,...,...,...,...,...,...,...,...,...,...
97613,97650,M'TSANGAMOUJI,MAYOTTE,MAYOTTE,Chef-lieu canton,96,21.55,5.0,"-12.7513099309, 45.0871696871","{""type"": ""Polygon"", ""coordinates"": [[[45.10168...",97650 M'TSANGAMOUJI
97614,97670,OUANGANI,MAYOTTE,MAYOTTE,Chef-lieu canton,175,18.28,6.6,"-12.8370955196, 45.1379095497","{""type"": ""Polygon"", ""coordinates"": [[[45.15401...",97670 OUANGANI
97615,97610,PAMANDZI,MAYOTTE,MAYOTTE,Chef-lieu canton,52,4.26,9.1,"-12.7961353309, 45.2842063102","{""type"": ""Polygon"", ""coordinates"": [[[45.29645...",97610 PAMANDZI
97616,97640,SADA,MAYOTTE,MAYOTTE,Chef-lieu canton,130,10.85,8.0,"-12.8611649609, 45.1185503145","{""type"": ""Polygon"", ""coordinates"": [[[45.13226...",97640 SADA
97617,97680,TSINGONI,MAYOTTE,MAYOTTE,Chef-lieu canton,147,34.26,9.2,"-12.7821666736, 45.1344279083","{""type"": ""Polygon"", ""coordinates"": [[[45.15256...",97680 TSINGONI

In [42]:
df.info()

<class 'pandas.DataFrame'>
Index: 36742 entries, 01001 to 97617
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Code Postal       36742 non-null  str
 1   Commune           36742 non-null  str
 2   Département       36742 non-null  str
 3   Région            36742 non-null  str
 4   Statut            36742 non-null  category
 5   Altitude Moyenne  36742 non-null  int64
 6   Superficie        36742 non-null  float64
 7   Population        36742 non-null  float64
 8   geo_point_2d      36742 non-null  str
 9   geo_shape         36742 non-null  str
 10  CP_Ville          36742 non-null  str
dtypes: category(1), float64(2), int64(1), str(7)
memory usage: 28.6 MB

In [43]:
df["Statut"]

Code INSEE
01001      Commune simple
01002      Commune simple
01004    Chef-lieu canton
01005      Commune simple
01006      Commune simple
               ...
97613    Chef-lieu canton
97614    Chef-lieu canton
97615    Chef-lieu canton
97616    Chef-lieu canton
97617    Chef-lieu canton
Name: Statut, Length: 36742, dtype: category
Categories (6, str): ['Commune simple' < 'Chef-lieu canton' < 'Sous-préfecture' < 'Préfecture' < 'Préfecture de région' < 'Capitale d'état']

In [45]:
df["Statut"].cat.codes

Code INSEE
01001    0
01002    0
01004    1
01005    0
01006    0
        ..
97613    1
97614    1
97615    1
97616    1
97617    1
Length: 36742, dtype: int8

In [52]:
df["geo_point_2d"].values[0]

'46.1534255214, 4.92611354223'

In [57]:
x = '46.1534255214, 4.92611354223'
float(x.split(', ')[0]), float(x.split(', ')[1])

(46.1534255214, 4.92611354223)

In [58]:
df["Latitude"] = df["geo_point_2d"].apply(lambda x: float(x.split(', ')[0]))
df["Longitude"] = df["geo_point_2d"].apply(lambda x: float(x.split(', ')[1]))
df

,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape,CP_Ville,Latitude,Longitude
Code INSEE,,,,,,,,,,,,,
01001,01400,L'ABERGEMENT-CLEMENCIAT,AIN,RHONE-ALPES,Commune simple,242,15.65,0.8,"46.1534255214, 4.92611354223","{""type"": ""Polygon"", ""coordinates"": [[[4.926273...",01400 L'ABERGEMENT-CLEMENCIAT,46.153426,4.926114
01002,01640,L'ABERGEMENT-DE-VAREY,AIN,RHONE-ALPES,Commune simple,483,9.12,0.2,"46.0091878776, 5.42801696363","{""type"": ""Polygon"", ""coordinates"": [[[5.430089...",01640 L'ABERGEMENT-DE-VAREY,46.009188,5.428017
01004,01500,AMBERIEU-EN-BUGEY,AIN,RHONE-ALPES,Chef-lieu canton,379,24.48,13.4,"45.9608475114, 5.3729257777","{""type"": ""Polygon"", ""coordinates"": [[[5.386190...",01500 AMBERIEU-EN-BUGEY,45.960848,5.372926
01005,01330,AMBERIEUX-EN-DOMBES,AIN,RHONE-ALPES,Commune simple,290,16.05,1.6,"45.9961799872, 4.91227250796","{""type"": ""Polygon"", ""coordinates"": [[[4.895580...",01330 AMBERIEUX-EN-DOMBES,45.996180,4.912273
01006,01300,AMBLEON,AIN,RHONE-ALPES,Commune simple,589,6.02,0.1,"45.7494989044, 5.59432017366","{""type"": ""Polygon"", ""coordinates"": [[[5.614854...",01300 AMBLEON,45.749499,5.594320
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97613,97650,M'TSANGAMOUJI,MAYOTTE,MAYOTTE,Chef-lieu canton,96,21.55,5.0,"-12.7513099309, 45.0871696871","{""type"": ""Polygon"", ""coordinates"": [[[45.10168...",97650 M'TSANGAMOUJI,-12.751310,45.087170
97614,97670,OUANGANI,MAYOTTE,MAYOTTE,Chef-lieu canton,175,18.28,6.6,"-12.8370955196, 45.1379095497","{""type"": ""Polygon"", ""coordinates"": [[[45.15401...",97670 OUANGANI,-12.837096,45.137910
97615,97610,PAMANDZI,MAYOTTE,MAYOTTE,Chef-lieu canton,52,4.26,9.1,"-12.7961353309, 45.2842063102","{""type"": ""Polygon"", ""coordinates"": [[[45.29645...",97610 PAMANDZI,-12.796135,45.284206
97616,97640,SADA,MAYOTTE,MAYOTTE,Chef-lieu canton,130,10.85,8.0,"-12.8611649609, 45.1185503145","{""type"": ""Polygon"", ""coordinates"": [[[45.13226...",97640 SADA,-12.861165,45.118550
97617,97680,TSINGONI,MAYOTTE,MAYOTTE,Chef-lieu canton,147,34.26,9.2,"-12.7821666736, 45.1344279083","{""type"": ""Polygon"", ""coordinates"": [[[45.15256...",97680 TSINGONI,-12.782167,45.134428

In [59]:
df.info()

<class 'pandas.DataFrame'>
Index: 36742 entries, 01001 to 97617
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Code Postal       36742 non-null  str
 1   Commune           36742 non-null  str
 2   Département       36742 non-null  str
 3   Région            36742 non-null  str
 4   Statut            36742 non-null  category
 5   Altitude Moyenne  36742 non-null  int64
 6   Superficie        36742 non-null  float64
 7   Population        36742 non-null  float64
 8   geo_point_2d      36742 non-null  str
 9   geo_shape         36742 non-null  str
 10  CP_Ville          36742 non-null  str
 11  Latitude          36742 non-null  float64
 12  Longitude         36742 non-null  float64
dtypes: category(1), float64(4), int64(1), str(7)
memory usage: 29.1 MB

In [79]:
df["geo_point_2d"].str.extract("(.+), (.+)").dtypes

0    str
1    str
dtype: object

In [80]:
df[["Latitude", "Longitude"]] = df["geo_point_2d"].str.extract("(.+), (.+)").astype(float)
df

,Code Postal,Commune,Département,Région,Statut,Altitude Moyenne,Superficie,Population,geo_point_2d,geo_shape,CP_Ville,Latitude,Longitude
Code INSEE,,,,,,,,,,,,,
01001,01400,L'ABERGEMENT-CLEMENCIAT,AIN,RHONE-ALPES,Commune simple,242,15.65,0.8,"46.1534255214, 4.92611354223","{""type"": ""Polygon"", ""coordinates"": [[[4.926273...",01400 L'ABERGEMENT-CLEMENCIAT,46.153426,4.926114
01002,01640,L'ABERGEMENT-DE-VAREY,AIN,RHONE-ALPES,Commune simple,483,9.12,0.2,"46.0091878776, 5.42801696363","{""type"": ""Polygon"", ""coordinates"": [[[5.430089...",01640 L'ABERGEMENT-DE-VAREY,46.009188,5.428017
01004,01500,AMBERIEU-EN-BUGEY,AIN,RHONE-ALPES,Chef-lieu canton,379,24.48,13.4,"45.9608475114, 5.3729257777","{""type"": ""Polygon"", ""coordinates"": [[[5.386190...",01500 AMBERIEU-EN-BUGEY,45.960848,5.372926
01005,01330,AMBERIEUX-EN-DOMBES,AIN,RHONE-ALPES,Commune simple,290,16.05,1.6,"45.9961799872, 4.91227250796","{""type"": ""Polygon"", ""coordinates"": [[[4.895580...",01330 AMBERIEUX-EN-DOMBES,45.996180,4.912273
01006,01300,AMBLEON,AIN,RHONE-ALPES,Commune simple,589,6.02,0.1,"45.7494989044, 5.59432017366","{""type"": ""Polygon"", ""coordinates"": [[[5.614854...",01300 AMBLEON,45.749499,5.594320
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97613,97650,M'TSANGAMOUJI,MAYOTTE,MAYOTTE,Chef-lieu canton,96,21.55,5.0,"-12.7513099309, 45.0871696871","{""type"": ""Polygon"", ""coordinates"": [[[45.10168...",97650 M'TSANGAMOUJI,-12.751310,45.087170
97614,97670,OUANGANI,MAYOTTE,MAYOTTE,Chef-lieu canton,175,18.28,6.6,"-12.8370955196, 45.1379095497","{""type"": ""Polygon"", ""coordinates"": [[[45.15401...",97670 OUANGANI,-12.837096,45.137910
97615,97610,PAMANDZI,MAYOTTE,MAYOTTE,Chef-lieu canton,52,4.26,9.1,"-12.7961353309, 45.2842063102","{""type"": ""Polygon"", ""coordinates"": [[[45.29645...",97610 PAMANDZI,-12.796135,45.284206
97616,97640,SADA,MAYOTTE,MAYOTTE,Chef-lieu canton,130,10.85,8.0,"-12.8611649609, 45.1185503145","{""type"": ""Polygon"", ""coordinates"": [[[45.13226...",97640 SADA,-12.861165,45.118550
97617,97680,TSINGONI,MAYOTTE,MAYOTTE,Chef-lieu canton,147,34.26,9.2,"-12.7821666736, 45.1344279083","{""type"": ""Polygon"", ""coordinates"": [[[45.15256...",97680 TSINGONI,-12.782167,45.134428

## 4. Filtrage des données

- Ecrire une fonction qui recherche les communes se terminant par un motif du type `"-mot1-mot2"` (par exemple `"-SUR-MER"`)

```python
def selection(mot1, mot2):
    pass
```

- Quelles villes contiennent deux "Z" (accolés, séparés par une seule lettre, séparés par un nombre quelconque de lettres, séparés par au moins une lettre) ?
- Quelles sont les dix terminaisons des noms de communes du type `"-mot1-mot2"` les plus fréquentes ?

In [68]:
def selection(mot1, mot2):
    pattern = f"-{mot1}-{mot2}"
    result = df.loc[df["Commune"].str.endswith(pattern), "Commune"].sort_values()
    return result

In [69]:
selection("SUR", "MER")

Code INSEE
76011    ANCRETTEVILLE-SUR-MER
50014        ANNEVILLE-SUR-MER
66008          ARGELES-SUR-MER
66016          BANYULS-SUR-MER
44010             BATZ-SUR-MER
                 ...
14739              VER-SUR-MER
76736        VEULETTES-SUR-MER
14745        VIERVILLE-SUR-MER
06159     VILLEFRANCHE-SUR-MER
14754          VILLERS-SUR-MER
Name: Commune, Length: 100, dtype: str

In [70]:
selection("SOUS", "BOIS")

Code INSEE
89020         ASNIERES-SOUS-BOIS
93005           AULNAY-SOUS-BOIS
60052         BEAUGIES-SOUS-BOIS
57128      CHARLEVILLE-SOUS-BOIS
93014           CLICHY-SOUS-BOIS
10136          EGUILLY-SOUS-BOIS
94033         FONTENAY-SOUS-BOIS
95316            JAGNY-SOUS-BOIS
78165       LES CLAYES-SOUS-BOIS
93057    LES PAVILLONS-SOUS-BOIS
93064            ROSNY-SOUS-BOIS
62762     SAINT-MICHEL-SOUS-BOIS
26335           SALLES-SOUS-BOIS
95660        VILLAINES-SOUS-BOIS
Name: Commune, dtype: str

In [72]:
df.loc[df["Commune"].str.contains("ZZ"), "Commune"]

Code INSEE
2A027              AZZANA
2A099             COZZANO
2A118             FOZZANO
2A259               REZZA
2A336    VALLE-DI-MEZZANA
2B143        LINGUIZZETTA
2B147               LOZZI
2B149       LUGO-DI-NAZZA
2B157             MAZZOLA
2B164    MONACIA-D'OREZZA
2B216            PIAZZALI
2B217            PIAZZOLE
2B222        PIE-D'OREZZA
2B236     POGGIO-DI-NAZZA
2B242      POGGIO-MEZZANA
2B291            STAZZONA
2B338      VALLE-D'OREZZA
2B347             VEZZANI
68030       BERGHOLTZZELL
Name: Commune, dtype: str

In [73]:
df.loc[df["Commune"].str.contains("Z.Z"), "Commune"]

Code INSEE
2A363                   ZOZA
43261               VEZEZOUX
71174    DEZIZE-LES-MARANGES
Name: Commune, dtype: str

In [74]:
df.loc[df["Commune"].str.contains("Z.*Z"), "Commune"]

Code INSEE
07161    MONTPEZAT-SOUS-BAUZON
09105       DAUMAZAN-SUR-ARIZE
09167           LEZAT-SUR-LEZE
11034         BELVEZE-DU-RAZES
11228      MAZEROLLES-DU-RAZES
                 ...
74311           VIUZ-EN-SALLAZ
78337            LIMETZ-VILLEZ
88404      ROZIERES-SUR-MOUZON
95282               GOUZANGREZ
97608                 DZAOUDZI
Name: Commune, Length: 67, dtype: str

In [75]:
df.loc[df["Commune"].str.contains("Z.+Z"), "Commune"]

Code INSEE
07161       MONTPEZAT-SOUS-BAUZON
09105          DAUMAZAN-SUR-ARIZE
09167              LEZAT-SUR-LEZE
11034            BELVEZE-DU-RAZES
11228         MAZEROLLES-DU-RAZES
11417          VILLARZEL-DU-RAZES
12294           VEZINS-DE-LEVEZOU
16378                 TAIZE-AIZIE
29008            BEUZEC-CAP-SIZUN
29176             PLONEVEZ-PORZAY
2A026              AZILONE-AMPAZA
2A362                       ZONZA
2A363                        ZOZA
31245               JUZET-D'IZAUT
34069         CAZOULS-LES-BEZIERS
34279    SAINT-NAZAIRE-DE-LADAREZ
34280      SAINT-NAZAIRE-DE-PEZAN
34310          THEZAN-LES-BEZIERS
42193             ROZIER-EN-DONZY
43131             MAZERAT-AUROUZE
43261                    VEZEZOUX
45026        BAZOCHES-SUR-LE-BETZ
45204          MEZIERES-LEZ-CLERY
45245          OUZOUER-SUR-TREZEE
47006          ALLEZ-ET-CAZENEUVE
54129           CIREY-SUR-VEZOUZE
54161         DOMEVRE-SUR-VEZOUZE
55024      AZANNES-ET-SOUMAZANNES
55178          ERIZE-SAINT-DIZIER
56090           INZINZAC-LOCHRIST
57433          MAIZIERES-LES-METZ
58116                   FLEZ-CUZY
59667                  ZERMEZEELE
63435           TOURZEL-RONZIERES
64063           ARZACQ-ARRAZIGUET
64373              MAZERES-LEZONS
65020           ARCIZAC-EZ-ANGLES
65203               GEZ-EZ-ANGLES
67347       OBERMODERN-ZUTZENDORF
69052           CHAZAY-D'AZERGUES
69229     SAINT-NIZIER-D'AZERGUES
71174         DEZIZE-LES-MARANGES
74310             VIUZ-LA-CHIESAZ
74311              VIUZ-EN-SALLAZ
78337               LIMETZ-VILLEZ
88404         ROZIERES-SUR-MOUZON
95282                  GOUZANGREZ
97608                    DZAOUDZI
Name: Commune, dtype: str

## 5. Recherche géographique

Définir une fonction :

```python
def ville(lat, long):
    pass
```

qui retourne le "CP Ville" de la commune la plus proche d'un point GPS.

Définir également :

```python
def gps2dec(deg, mn, sec):
    pass
```

qui convertit les coordonnées GPS (degrés, minutes, secondes) en degrés décimaux.

Exercice final :

- choisir une petite commune française
- récupérer ses coordonnées GPS sur Wikipédia
- utiliser les fonctions `gps2dec()` puis `ville()` pour retrouver la commune

In [95]:
def ville(lat, long):
    dist = np.sqrt((df["Latitude"] - lat)**2 + (df["Longitude"] - long)**2)
    result = df.loc[dist.idxmin(), "CP_Ville"]
    return result

In [81]:
np.sqrt((df["Latitude"] - 0)**2 + (df["Longitude"] - 0)**2)

Code INSEE
01001    46.415572
01002    46.328271
01004    46.273835
01005    46.257745
01006    46.090271
           ...
97613    46.855616
97614    46.927837
97615    47.057416
97616    46.915809
97617    46.909491
Length: 36742, dtype: float64

In [83]:
ville(45, 0)

"33660 SAINT-SEURIN-SUR-L'ISLE"

In [86]:
def gps2dec(deg, mn, sec):
    return deg + mn / 60 + sec / 3600

In [88]:
# 48° 48′ 00″ nord, 2° 42′ 19″ est
ville(gps2dec(48, 48, 0), gps2dec(2, 42, 19))

'77135 PONTCARRE'

In [89]:
# 44° 35′ 58″ nord, 5° 14′ 53″ est
ville(gps2dec(44, 35, 58), gps2dec(5, 14, 53))

'26340 ROCHEFOURCHAT'

In [93]:
def ville2(lat, long):
    dist2 = (df["Latitude"] - lat)**2 + (df["Longitude"] - long)**2
    result = df.loc[dist2.idxmin(), "CP_Ville"]
    return result

In [94]:
# 44° 35′ 58″ nord, 5° 14′ 53″ est
ville2(gps2dec(44, 35, 58), gps2dec(5, 14, 53))

'26340 ROCHEFOURCHAT'

## 6. Géométrie

- Décoder les données JSON de la colonne "geo_shape"
- Donner le décompte des différentes valeurs associées à la clé "type"
- Donner le décompte des longueurs des listes associées à la clé "coordinates"
- Quelles sont les "CP Ville" des communes de type "Polygon" et dont la longueur des listes accédées avec la clé "coordinates" vaut 2 ?

In [98]:
df["geo_shape"].values[0]

'{"type": "Polygon", "coordinates": [[[4.92627342692396, 46.1200517234555], [4.92199538031264, 46.12069170563269], [4.921996260482057, 46.12663667307488], [4.90936269187648, 46.129164756530656], [4.916016986429157, 46.14461766984426], [4.903080786126749, 46.157977074275074], [4.904571300671208, 46.16096059498421], [4.910603091203733, 46.180432597608316], [4.914119126867876, 46.18271538441311], [4.932895432675545, 46.18304616431434], [4.938729478686701, 46.17383114520867], [4.933038591703602, 46.16429901579509], [4.958286230120842, 46.153246666893935], [4.943330383388636, 46.145964148557894], [4.939154593056283, 46.12938048470421], [4.931056072485923, 46.12087123131487], [4.92627342692396, 46.1200517234555]]]}'

In [99]:
import json

In [100]:
x = df["geo_shape"].values[0]
json.loads(x)

{'type': 'Polygon',
 'coordinates': [[[4.92627342692396, 46.1200517234555],
   [4.92199538031264, 46.12069170563269],
   [4.921996260482057, 46.12663667307488],
   [4.90936269187648, 46.129164756530656],
   [4.916016986429157, 46.14461766984426],
   [4.903080786126749, 46.157977074275074],
   [4.904571300671208, 46.16096059498421],
   [4.910603091203733, 46.180432597608316],
   [4.914119126867876, 46.18271538441311],
   [4.932895432675545, 46.18304616431434],
   [4.938729478686701, 46.17383114520867],
   [4.933038591703602, 46.16429901579509],
   [4.958286230120842, 46.153246666893935],
   [4.943330383388636, 46.145964148557894],
   [4.939154593056283, 46.12938048470421],
   [4.931056072485923, 46.12087123131487],
   [4.92627342692396, 46.1200517234555]]]}

In [101]:
type(json.loads(x))

dict

In [102]:
json.loads(x)["type"]

'Polygon'

In [103]:
json.loads(x)["coordinates"]

[[[4.92627342692396, 46.1200517234555],
  [4.92199538031264, 46.12069170563269],
  [4.921996260482057, 46.12663667307488],
  [4.90936269187648, 46.129164756530656],
  [4.916016986429157, 46.14461766984426],
  [4.903080786126749, 46.157977074275074],
  [4.904571300671208, 46.16096059498421],
  [4.910603091203733, 46.180432597608316],
  [4.914119126867876, 46.18271538441311],
  [4.932895432675545, 46.18304616431434],
  [4.938729478686701, 46.17383114520867],
  [4.933038591703602, 46.16429901579509],
  [4.958286230120842, 46.153246666893935],
  [4.943330383388636, 46.145964148557894],
  [4.939154593056283, 46.12938048470421],
  [4.931056072485923, 46.12087123131487],
  [4.92627342692396, 46.1200517234555]]]

In [104]:
geo_shape = df["geo_shape"].apply(lambda x: json.loads(x))
geo_shape

Code INSEE
01001    {'type': 'Polygon', 'coordinates': [[[4.926273...
01002    {'type': 'Polygon', 'coordinates': [[[5.430089...
01004    {'type': 'Polygon', 'coordinates': [[[5.386190...
01005    {'type': 'Polygon', 'coordinates': [[[4.895580...
01006    {'type': 'Polygon', 'coordinates': [[[5.614854...
                               ...
97613    {'type': 'Polygon', 'coordinates': [[[45.10168...
97614    {'type': 'Polygon', 'coordinates': [[[45.15401...
97615    {'type': 'Polygon', 'coordinates': [[[45.29645...
97616    {'type': 'Polygon', 'coordinates': [[[45.13226...
97617    {'type': 'Polygon', 'coordinates': [[[45.15256...
Name: geo_shape, Length: 36742, dtype: object

In [105]:
geo_shape = df["geo_shape"].apply(json.loads)
geo_shape

Code INSEE
01001    {'type': 'Polygon', 'coordinates': [[[4.926273...
01002    {'type': 'Polygon', 'coordinates': [[[5.430089...
01004    {'type': 'Polygon', 'coordinates': [[[5.386190...
01005    {'type': 'Polygon', 'coordinates': [[[4.895580...
01006    {'type': 'Polygon', 'coordinates': [[[5.614854...
                               ...
97613    {'type': 'Polygon', 'coordinates': [[[45.10168...
97614    {'type': 'Polygon', 'coordinates': [[[45.15401...
97615    {'type': 'Polygon', 'coordinates': [[[45.29645...
97616    {'type': 'Polygon', 'coordinates': [[[45.13226...
97617    {'type': 'Polygon', 'coordinates': [[[45.15256...
Name: geo_shape, Length: 36742, dtype: object

In [107]:
geo_shape.apply(lambda d: d["type"]).value_counts()

geo_shape
Polygon         36670
MultiPolygon       72
Name: count, dtype: int64

### Tests

In [11]:
# 1) tests unitaires de la fonction lecture_geo

import unittest

class PandasTest(unittest.TestCase):
    """
    Tests unitaires du chargement du fichier :
    correspondance-code-insee-code-postal.csv
    """
        
    def test_1_dataframe(self):
        df = lecture_geo()
        self.assertTrue(isinstance(df, pd.DataFrame))
        
    def test_2_columns(self):
        df = lecture_geo()
        self.assertEqual(len(df.columns), 10)
        
    def test_3_index(self):
        df = lecture_geo()
        self.assertTrue(isinstance(df.index, pd.Index))
        
    def test_4_index_name(self):
        df = lecture_geo()
        self.assertEqual(df.index.name, "Code INSEE")
        
    def test_5_index_sort(self):
        df = lecture_geo()
        self.assertEqual(df.index.min(), df.index[0])
        self.assertEqual(df.index.max(), df.index[-1])

In [12]:
# 2) fonction run_tests

def run_tests():
    test_suite = unittest.TestLoader().loadTestsFromTestCase(PandasTest)
    runner = unittest.TextTestRunner(verbosity=2)
    runner.run(test_suite)

In [17]:
# 3) exécution des tests
run_tests()

test_1_dataframe (__main__.PandasTest.test_1_dataframe) ... ok
test_2_columns (__main__.PandasTest.test_2_columns) ... ok
test_3_index (__main__.PandasTest.test_3_index) ... ok
test_4_index_name (__main__.PandasTest.test_4_index_name) ... ok
test_5_index_sort (__main__.PandasTest.test_5_index_sort) ... ok

----------------------------------------------------------------------
Ran 5 tests in 2.124s

OK